apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-svc
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  selector:
    role: db
    env: {{ .Values.global.namespace | default "default" }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}