apiVersion: apps/v1
kind: Deployment

metadata: 
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    role: frontend
    env: {{ .Values.global.namespace | default "default" }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      role: frontend
      env: {{ .Values.global.namespace | default "default" }}
  template:
    metadata:
      labels:
        role: frontend
        env: {{ .Values.global.namespace | default "default" }}

    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}

          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: REACT_APP_BACKEND_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: PORT_frontend

          resources:
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | quote }}